[project]
name = "cognee-azure-ai-search-adapter"
version = "1.0.0"
description = "Azure AI search vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "azure-search-documents>=11.4.0",
    "azure-core>=1.29.0"
]


[tool.poetry]
package-mode = false