[project]
name = "cognee-community-graph-adapter-networkx"
version = "1.0.0"
description = "Networkx graph database adapter for cognee"
readme = "README.md"
requires-python =  ">=3.11,<=3.13"
dependencies = [
    "networkx>=3.4.2,<4",
    "cognee>=0.1.41"
]
