line-length = 100
target-version = "py311"

exclude = [
  ".git",
  ".ruff_cache",
  "__pycache__",
  "node_modules",
  "build",
  "dist",
]

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "W",  # pycodestyle warnings
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = []
fixable = ["ALL"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

