[project]
name = "cognee-community-vector-adapter-milvus"
version = "1.0.0"
description = "Milvus vector database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "pymilvus>=2.5.0,<3",
    "milvus-lite>=2.4.0; sys_platform != 'win32'",
    "cognee>=0.2.0.dev0"
]