[project]
name = "cognee-milvus-adapter"
version = "0.1.0"
description = "Community-contributed Milvus adapter for Cognee"
authors = [
    {name = "Cognee Community", email = "community@cognee.ai"},
]
readme = "README.md"
license = {text = "Apache-2.0"}
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "pymilvus>=2.5.0,<3",
    "milvus-lite>=2.4.0; sys_platform != 'win32'",
]

[project.urls]
Homepage = "https://github.com/topoteretes/cognee"
Repository = "https://github.com/topoteretes/cognee"
Documentation = "https://docs.cognee.ai"
Issues = "https://github.com/topoteretes/cognee/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cognee_milvus_adapter"]

[tool.hatch.build.targets.sdist]
include = [
    "/cognee_milvus_adapter",
    "/README.md",
] 