[project]
name = "cognee-community-hybrid-adapter-falkor"
version = "0.0.1"
description = "Falkor hybrid database adapter for cognee"
readme = "README.md"
requires-python = ">=3.11,<=3.13"
dependencies = [
    "falkor>=0.1.0",
    "cognee>=0.2.0.dev0"
]