[project]
name = "cognee-community-observability-keywordsai"
version = "1.0.0"
description = "Keywords AI observability integration for Cognee"
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "cognee>=0.2.1",
    "keywordsai-tracing>=0.0.41,<0.0.44"
]
