name: Community Graph DB Tests

on:
  workflow_call:
    inputs:
      databases:
        required: false
        type: string
        default: "all"
        description: "Which graph databases to test (comma-separated list or 'all')"
      python-version:
        required: false
        type: string
        default: "3.11.x"
    secrets:
      LLM_MODEL:
        required: true
      LLM_ENDPOINT:
        required: true
      LLM_API_KEY:
        required: true
      LLM_API_VERSION:
        required: true
      EMBEDDING_MODEL:
        required: true
      EMBEDDING_ENDPOINT:
        required: true
      EMBEDDING_API_KEY:
        required: true
      EMBEDDING_API_VERSION:
        required: true

jobs:
  test-networkx:
    name: "NetworkX Community Adapter Test"
    runs-on: ubuntu-22.04
    if: ${{ inputs.databases == 'all' || contains(inputs.databases, 'networkx') }}
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Community Setup
        uses: ./.github/actions/community_setup
        with:
          python-version: ${{ inputs.python-version }}
          package-path: packages/graph/networkx

      - name: Run NetworkX Tests
        env:
          ENV: 'dev'
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
          GRAPH_DATABASE_PROVIDER: 'networkx'
        working-directory: ./packages/graph/networkx
        run: poetry run python example.py

  test-memgraph:
    name: "Memgraph Community Adapter Test"
    if: ${{ inputs.databases == 'all' || contains(inputs.databases, 'memgraph') }}
    uses: ./.github/workflows/test_memgraph.yml
    secrets: inherit

  test-falkordb:
    name: "FalkorDB Community Adapter Test"
    if: ${{ inputs.databases == 'all' || contains(inputs.databases, 'falkordb') }}
    uses: ./.github/workflows/test_falkordb.yml
    secrets: inherit 