name: Ruff Lint and Format

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    name: Run Linting
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: "3.11"

      - name: Run Linting
        uses: astral-sh/ruff-action@v2

  format-check:
    name: Run Formatting Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cognee Setup
        uses: ./.github/actions/cognee_setup
        with:
          python-version: "3.11"

      - name: Run Formatting Check
        uses: astral-sh/ruff-action@v2
        with:
          args: "format --check"

