name: Test Milvus Community Adapter

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/milvus/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/milvus/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-milvus:
    name: "Milvus Community Adapter Test"
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Community Setup
        uses: ./.github/actions/community_setup
        with:
          python-version: '3.11.x'
          package-path: packages/vector/milvus

      - name: Start Milvus using official script
        run: |
          curl -sfL https://raw.githubusercontent.com/milvus-io/milvus/master/scripts/standalone_embed.sh -o standalone_embed.sh
          bash standalone_embed.sh start
          echo "Milvus started with official script"

      - name: Wait for Milvus to be ready
        run: |
          for i in {1..60}; do
            if curl -f http://localhost:9091/healthz 2>/dev/null; then
              echo "Milvus is ready"
              break
            fi
            echo "Waiting for Milvus... (attempt $i/60)"
            sleep 5
          done
          # Verify Milvus is actually responding
          curl -f curl -f http://localhost:9091/healthz || (echo "Milvus failed to start" && exit 1)

      - name: Run Milvus Tests
        env:
          ENV: 'dev'
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
          VECTOR_DB_PROVIDER: 'milvus'
          VECTOR_DB_URL: 'http://localhost:19530'
        working-directory: ./packages/vector/milvus
        run: poetry run python examples/example.py