name: Test Qdrant Community Adapter

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/qdrant/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/qdrant/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-qdrant:
    name: "Qdrant Community Adapter Test"
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Community Setup
        uses: ./.github/actions/community_setup
        with:
          python-version: '3.11.x'
          package-path: packages/vector/qdrant

      - name: Run Qdrant Tests
        env:
          ENV: 'dev'
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
          VECTOR_DB_PROVIDER: 'qdrant'
          VECTOR_DB_URL: ${{ secrets.QDRANT_API_URL }}
          VECTOR_DB_KEY: ${{ secrets.QDRANT_API_KEY }}
        working-directory: ./packages/vector/qdrant
        run: poetry run python example.py 