name: Test Redis Community Adapter

on:
  workflow_dispatch:
  push:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/redis/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'packages/vector/redis/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-redis:
    name: "Redis Community Adapter Test"
    runs-on: ubuntu-22.04
    services:
      redis:
        image: redis/redis-stack-server:7.4.0-v1
        ports:
          - 6379:6379
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Community Setup
        uses: ./.github/actions/community_setup
        with:
          python-version: '3.11.x'
          package-path: packages/vector/redis

      - name: Run Redis Tests
        env:
          ENV: 'dev'
          LLM_MODEL: ${{ secrets.LLM_MODEL }}
          LLM_ENDPOINT: ${{ secrets.LLM_ENDPOINT }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_API_VERSION: ${{ secrets.LLM_API_VERSION }}
          EMBEDDING_MODEL: ${{ secrets.EMBEDDING_MODEL }}
          EMBEDDING_ENDPOINT: ${{ secrets.EMBEDDING_ENDPOINT }}
          EMBEDDING_API_KEY: ${{ secrets.EMBEDDING_API_KEY }}
          EMBEDDING_API_VERSION: ${{ secrets.EMBEDDING_API_VERSION }}
          VECTOR_DB_PROVIDER: 'redis'
          VECTOR_DB_URL: 'redis://localhost:6379'
        working-directory: ./packages/vector/redis
        run: |
          if [ -f "examples/example.py" ]; then
            poetry run python examples/example.py
          else
            poetry run python example.py
          fi 